# Generated by Django 3.2.15 on 2022-11-06 23:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('cedula_usuario', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Usuarios_Sivore',
                'ordering': ['first_name'],
                'permissions': (('Administrador', 'Permisos de Administrador'), ('Censista', 'Permisos de Censista'), ('Supervisor', 'Permisos de Supervisor')),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
