# Generated by Django 4.1.3 on 2022-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name'], 'permissions': (('Administrador', 'Permisos de Administrador'), ('Censista', 'Permisos de Censista'), ('Supervisor', 'Permisos de Supervisor')), 'verbose_name_plural': 'Usuarios'},
        ),
    ]
