# Generated by Django 3.2.15 on 2022-12-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name'], 'permissions': (('Administrador', 'Permisos de Administrador'), ('Censista', 'Permisos de Censista'), ('Supervisor', 'Permisos de Supervisor'), ('SuperForestal', 'Permisos de Supervisor Forestal')), 'verbose_name_plural': 'Usuarios'},
        ),
    ]
