# Generated by Django 3.2.15 on 2022-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='', upload_to='fotos_usuarios/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
