# Generated by Django 3.2.15 on 2022-12-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20221208_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Grupo',
            field=models.TextField(null=True),
        ),
    ]
