# Generated by Django 4.1.3 on 2022-12-17 14:36

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to=usuarios.models.Usuario._generar_ruta_imagen),
        ),
    ]
