# Generated by Django 4.1.3 on 2022-12-17 17:00

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='fotos_usuarios/image-default.png', upload_to=usuarios.models.Usuario._generar_ruta_imagen),
        ),
    ]
