# Generated by Django 3.2.15 on 2022-10-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arbolid', models.BigIntegerField()),
                ('codigo', models.TextField()),
                ('placa', models.TextField()),
                ('qrcode', models.CharField(max_length=100)),
                ('barrio', models.TextField()),
                ('direccion', models.TextField()),
                ('comuna', models.CharField(max_length=2)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('norte', models.FloatField()),
                ('este', models.FloatField()),
                ('nombre_comun', models.TextField()),
                ('nombre_cientifico', models.TextField()),
                ('familia', models.TextField()),
                ('genero', models.TextField()),
                ('estado_madurez', models.TextField()),
                ('estado_registro', models.TextField()),
                ('especie', models.TextField()),
                ('tipo_vegetacion', models.TextField()),
                ('area', models.FloatField()),
                ('perimetro', models.FloatField()),
                ('hito', models.TextField()),
                ('estado_conservacion', models.TextField()),
                ('intervencion', models.TextField()),
                ('cobertura', models.TextField()),
                ('emplazamiento', models.TextField()),
                ('confinamiento', models.BooleanField()),
                ('dist_confinamiento', models.IntegerField()),
                ('foto1', models.ImageField(upload_to='fotos_arboles/')),
                ('foto2', models.ImageField(upload_to='fotos_arboles/')),
                ('foto3', models.ImageField(upload_to='fotos_arboles/')),
                ('foto4', models.ImageField(upload_to='fotos_arboles/')),
                ('observaciones', models.TextField()),
                ('estado', models.TextField()),
                ('fecha_creado', models.DateTimeField()),
                ('modificadopor', models.TextField()),
                ('actualizado', models.DateTimeField()),
                ('version_fecha', models.DateField()),
            ],
            options={
                'db_table': 'arbol',
                'ordering': ['arbolid'],
            },
        ),
    ]
