# Generated by Django 4.1.1 on 2022-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arbolid', models.BigIntegerField()),
                ('codigo', models.TextField()),
                ('placa', models.TextField()),
                ('qrcode', models.CharField(max_length=100)),
                ('barrio', models.TextField()),
                ('comuna', models.CharField(max_length=2)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('norte', models.FloatField()),
                ('este', models.FloatField()),
                ('nombre_comun', models.TextField()),
                ('familia', models.TextField()),
                ('genero', models.TextField()),
                ('especie', models.TextField()),
                ('tipo_vegetacion', models.TextField()),
                ('madurez', models.TextField()),
                ('area', models.FloatField()),
                ('perimetro', models.FloatField()),
                ('hito', models.TextField()),
                ('estado_conservacion', models.TextField()),
                ('intervencion', models.TextField()),
                ('cobertura', models.TextField()),
                ('confinamiento', models.IntegerField()),
                ('dist_confinamiento', models.IntegerField()),
                ('emplazamiento', models.TextField()),
                ('foto1', models.TextField()),
                ('foto2', models.TextField()),
                ('foto3', models.TextField()),
                ('foto4', models.TextField()),
                ('observaciones', models.TextField()),
                ('estado', models.TextField()),
                ('fecha_creado', models.DateTimeField()),
                ('modificadopor', models.TextField()),
                ('actualizado', models.DateTimeField()),
                ('version_fecha', models.DateField()),
            ],
            options={
                'db_table': 'arbol',
                'ordering': ['fecha_creado'],
            },
        ),
    ]
