# Generated by Django 3.2.15 on 2022-10-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
