# Generated by Django 4.1.1 on 2022-09-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbol',
            options={},
        ),
        migrations.AlterModelTable(
            name='arbol',
            table=None,
        ),
    ]
