# Generated by Django 4.1.1 on 2022-09-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_arbol_options_alter_arbol_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbol',
            options={'ordering': ['arbolid']},
        ),
        migrations.AlterModelTable(
            name='arbol',
            table='arbol',
        ),
    ]
