# Generated by Django 3.2.15 on 2022-10-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_arbol_fecha_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='actualizado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='version_fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
